import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Clock3, MapPin, MessageCircle, Phone, Mail, Instagram } from "lucide-react";
import { Eyebrow, PageIntro } from "@/components/ui";
import { hospital, whatsappUrl } from "@/lib/hospital";
import { HospitalBuilding } from "@/components/hospital-visit";

export const metadata: Metadata = { title: "Contact & directions" };
export default function ContactPage() {
  return <><PageIntro eyebrow="Contact & directions" title={<>Close to home.<br /><em>Easy to reach.</em></>} description="Call us, send a message, or find your way to LVR. Our team can help you plan the next step." /><section className="section"><div className="container contact-grid"><div><Eyebrow>LET’S CONNECT</Eyebrow><h2>A helping hand<br /><em>is a call away.</em></h2><div className="contact-method"><span><Phone size={23} /></span><div><h3>Call our reception</h3><a href={hospital.phoneHref}>{hospital.phone}</a><a href={hospital.secondaryPhoneHref}>{hospital.secondaryPhone}</a><small>For appointments, enquiries, and urgent care.</small></div></div><div className="contact-method"><span><MessageCircle size={23} /></span><div><h3>Message on WhatsApp</h3><a href={whatsappUrl()} target="_blank" rel="noopener noreferrer">+91 97910 39302 <ArrowUpRight size={17} /></a><small>For appointment requests and general enquiries.</small></div></div><div className="contact-method"><span><Clock3 size={23} /></span><div><h3>Open 24 hours, every day</h3><p>Specialist consultation times vary.</p><Link href="/doctors" className="text-link">View doctor information <ArrowUpRight size={15} /></Link></div></div><div className="contact-method"><span><Mail size={23} /></span><div><h3>Email the hospital</h3><a className="hospital-email" href={`mailto:${hospital.email}`}>{hospital.email}</a><small>General enquiries and careers. For urgent care, call reception.</small></div></div><div className="contact-method"><span><Instagram size={23} /></span><div><h3>Follow hospital updates</h3><a href={hospital.instagram} target="_blank" rel="noopener noreferrer">LVR on Instagram <ArrowUpRight size={17} /></a><a href={hospital.linksUrl} target="_blank" rel="noopener noreferrer">Hospital link hub <ArrowUpRight size={17} /></a></div></div></div><div className="address-card"><HospitalBuilding caption={false} /><div className="address-copy"><span className="address-label"><MapPin size={16} />SATHUPALLY, TELANGANA</span><h2>Find us in your<br /><em>neighbourhood.</em></h2><p>{hospital.address}</p><a className="button" href={hospital.mapsUrl} target="_blank" rel="noopener noreferrer">Open in Google Maps <ArrowUpRight size={18} /></a><small>Call reception if you need help with directions.</small></div></div></div></section></>;
}
