import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, CalendarDays, ClipboardList, Clock3, IndianRupee, Phone } from "lucide-react";
import { CareCta, CheckList, Eyebrow, FaqList, PageIntro } from "@/components/ui";
import { hospital } from "@/lib/hospital";

export const metadata: Metadata = { title: "Patient guide" };
export default function PatientGuidePage() {
  return <><PageIntro eyebrow="Patient guide" title={<>A little guidance.<br /><em>A more comfortable visit.</em></>} description="From planning your consultation to finding our front door, here’s what to know before you come." /><section className="section"><div className="container"><div className="three-grid guide-grid"><article className="guide-card"><CalendarDays size={29} strokeWidth={1.4} /><h2>Before your visit</h2><p>Registration is available online and at the hospital. Request an appointment through WhatsApp or call reception. Wait for the team to confirm your doctor and time before making plans.</p><Link href="/appointment" className="text-link">Request a visit <ArrowUpRight size={16} /></Link></article><article className="guide-card"><ClipboardList size={29} strokeWidth={1.4} /><h2>What to bring</h2><CheckList items={["Previous prescriptions, if available", "Relevant medical reports", "Your current medicines list", "Any questions for your doctor"]} /></article><article className="guide-card"><Clock3 size={29} strokeWidth={1.4} /><h2>Consultation hours</h2><p>Our hospital is open 24/7. Specialist schedules vary, and appointments depend on availability.</p><Link href="/doctors" className="text-link">See our doctors <ArrowUpRight size={16} /></Link></article></div><div className="fee-panel"><IndianRupee size={32} strokeWidth={1.3} /><div><h2>Consultation fees</h2><p>Consultation by doctor: <strong>₹300–₹500</strong> <span>·</span> Emergency consultation after 9:30 PM: <strong>₹500</strong></p><small>See your doctor’s profile for their listed fee and confirm applicable charges with reception before visiting. Tests, medicines, and procedures may be charged separately.</small></div></div><div className="visitor-details"><article><h2>Payments & insurance</h2><p>Cash and digital payments are accepted. Cashless insurance is not currently available. Bills are provided; check reimbursement eligibility directly with your insurer.</p></article><article><h2>During your stay</h2><p>Single rooms, wards, and AC and non-AC deluxe rooms are available. Ask the care team about visiting arrangements for your ward and any patient-specific requirements.</p></article><article><h2>Access & ambulance</h2><p>Parking, a lift, and wheelchair access are available. Ambulance assistance is available around the clock through reception.</p><Link href="/facilities" className="text-link">See hospital facilities <ArrowUpRight size={16} /></Link></article></div><div className="help-panel"><div><h2>Need urgent help?</h2><p>Please call the hospital directly. Do not wait for an online appointment response.</p></div><a className="button" href={hospital.phoneHref}><Phone size={17} />{hospital.phone}</a></div></div></section><section className="section section-tinted" id="questions"><div className="container faq-grid"><div><Eyebrow>YOUR QUESTIONS, ANSWERED</Eyebrow><h2>Good to know<br /><em>before you go.</em></h2></div><FaqList /></div></section><CareCta /></>;
}
